# Generated by Django 2.0 on 2018-08-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='paradgme',
            new_name='paradigm',
        ),
    ]
