# Generated by Django 2.0 on 2018-08-26 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_paradigm_programmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='paradigm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.Paradigm'),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='languages',
            field=models.ManyToManyField(to='language.Language'),
        ),
    ]
